/**
 * The single typed HTTP client for the TradingBot API.
 *
 * ALL backend calls go through this file's `api` instance -- a hand-written
 * fetch to the API elsewhere in the app is a defect (CLAUDE.md). Types come
 * from `schema.ts`, generated by `openapi-typescript` from the backend's live
 * OpenAPI spec (see frontend/openapi.json and the `api-client-regen` skill).
 * Regenerate schema.ts after any backend contract change; never hand-patch
 * types here.
 *
 * Auth: every route except /health requires `Authorization: Bearer <token>`
 * where token is the current Supabase Auth session's access_token. The
 * middleware below reads the session fresh on every request (Supabase's SDK
 * auto-refreshes it) and attaches it. The UI never talks to Webull or holds
 * a broker/Anthropic key (Invariant 2) -- this client only ever talks to our
 * own FastAPI backend at VITE_API_URL.
 */
import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./schema";
import { supabase } from "../lib/supabase";

const baseUrl = import.meta.env.VITE_API_URL;

if (!baseUrl) {
  throw new Error("Missing VITE_API_URL -- check frontend/.env");
}

/** Thrown by query/mutation functions when the API refuses a request as
 * unauthenticated (401) or non-owner (403). Callers can catch this
 * specifically to route back to the login screen. */
export class AuthError extends Error {
  status: 401 | 403;

  constructor(status: 401 | 403) {
    super(status === 401 ? "not authenticated" : "not authorized");
    this.status = status;
  }
}

const authMiddleware: Middleware = {
  async onRequest({ request }) {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    if (token) {
      request.headers.set("Authorization", `Bearer ${token}`);
    }
    return request;
  },
};

export const api = createClient<paths>({ baseUrl });
api.use(authMiddleware);

/** Raise AuthError for 401/403 responses so callers don't have to check
 * status codes themselves for the auth-specific cases. */
export function assertNotAuthError(status: number): void {
  if (status === 401 || status === 403) {
    throw new AuthError(status);
  }
}
