/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return the current bot settings (frozen flag, caps, staleness).
         */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Settings
         * @description Apply a partial update to the owner's control surface, return the result.
         *
         *     Owner-gated (unreachable without the single-owner auth gate). Writes
         *     `settings` in Supabase only -- never Webull (Invariant 2). `owner` (the
         *     authenticated owner's id) is recorded as `updated_by`, which drives the
         *     `settings_history` audit trigger. Only fields the caller actually supplied
         *     are forwarded; omitted fields are left unchanged. A DB failure maps to 503
         *     (fail closed); the helper's "no fields" guard maps to 422 (Pydantic
         *     normally rejects an empty body first).
         */
        patch: operations["update_settings_settings_patch"];
        trace?: never;
    };
    "/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Decisions
         * @description Return decisions newest-first (`decided_at desc`), paginated.
         */
        get: operations["get_decisions_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Account
         * @description Return the most recent equity snapshot, or 404 if none recorded yet.
         */
        get: operations["get_account_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BotSettings
         * @description Mirrors `settings` (20260719000004_settings.sql).
         *
         *     The one intentionally mutable table: the owner's entire control surface
         *     (freeze/unfreeze, buy-power cap, daily-loss cap, per-trade cap, staleness
         *     threshold) is "mutate this row". Named `BotSettings` rather than `Settings`
         *     to avoid collision with `app.core.config.Settings` (process env-var config)
         *     -- see module docstring. Born frozen=True with all caps at 0.00 in the seed
         *     migration; the worker must treat an unreadable row the same way (fail
         *     closed, CLAUDE.md invariant #2/#3).
         */
        BotSettings: {
            /**
             * Id
             * @default true
             * @constant
             */
            id: true;
            /** Frozen */
            frozen: boolean;
            /** Buy Power Cap */
            buy_power_cap: string;
            /** Max Daily Loss */
            max_daily_loss: string;
            /** Max Per Trade Cap */
            max_per_trade_cap: string;
            /** Staleness Threshold Seconds */
            staleness_threshold_seconds: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by?: string | null;
        };
        /**
         * Decision
         * @description Mirrors `decisions` (20260719000006_decisions.sql).
         *
         *     Append-only per CLAUDE.md invariant #5: `reject_update_or_delete()` triggers
         *     on UPDATE and DELETE make mutation impossible for every role, including
         *     service_role. Frozen here so application code cannot even attempt to mutate
         *     an in-memory instance; corrections are new rows, never edits.
         */
        Decision: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Symbol */
            symbol: string;
            action: components["schemas"]["DecisionAction"];
            /** Rules Fired */
            rules_fired?: unknown[] | {
                [key: string]: unknown;
            };
            /** Llm Rationale */
            llm_rationale?: string | null;
            /** Thesis Id */
            thesis_id?: string | null;
            /** Conviction */
            conviction?: string | null;
            /** Market Data As Of */
            market_data_as_of?: string | null;
            /** Settings Snapshot */
            settings_snapshot?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DecisionAction
         * @description decisions.action -- 20260719000006_decisions.sql: decisions_action_valid.
         * @enum {string}
         */
        DecisionAction: "buy" | "sell" | "hold" | "no_trade";
        /**
         * EquitySnapshot
         * @description Mirrors `equity_snapshots` (20260719000010_equity_snapshots.sql).
         *
         *     Drives the equity curve and the SPY buy-and-hold benchmark comparison
         *     (CLAUDE.md success criterion). Not append-only -- the migration's own
         *     comment notes a same-day snapshot may reasonably be recomputed intraday
         *     (worker restart, corrected reconciliation) -- left mutable.
         */
        EquitySnapshot: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Snapshot Date
             * Format: date
             */
            snapshot_date: string;
            /** Account Equity */
            account_equity: string;
            /** Cash Balance */
            cash_balance: string;
            /** Buying Power */
            buying_power: string;
            /** Spy Close Price */
            spy_close_price?: string | null;
            /** Spy Benchmark Equity */
            spy_benchmark_equity?: string | null;
            /**
             * Is Paper
             * @default true
             */
            is_paper: boolean;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SettingsUpdate
         * @description Partial update to the singleton `settings` row (owner control surface).
         *
         *     PATCH semantics: every field is optional; an omitted field is left
         *     unchanged (coalesced by the DB helper). Validation mirrors the SQL CHECK
         *     constraints -- caps are non-negative, `staleness_threshold_seconds` is
         *     positive -- so bad input fails 422 at the edge instead of hitting the
         *     database. Money fields are `Decimal` (the same annotated types the response
         *     model uses), never float. Unknown fields are rejected (`extra="forbid"`) so
         *     a caller cannot smuggle in `id`/`updated_at`/`updated_by`, and an all-empty
         *     body is rejected because there is nothing to update.
         */
        SettingsUpdate: {
            /** Frozen */
            frozen?: boolean | null;
            /** Buy Power Cap */
            buy_power_cap?: string | null;
            /** Max Daily Loss */
            max_daily_loss?: string | null;
            /** Max Per Trade Cap */
            max_per_trade_cap?: string | null;
            /** Staleness Threshold Seconds */
            staleness_threshold_seconds?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotSettings"];
                };
            };
        };
    };
    update_settings_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_decisions_decisions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquitySnapshot"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
