-- orders: append-only audit log of every order the worker submits to Webull.
--
-- CLAUDE.md invariant #4: client_order_id is written BEFORE submission and is the
-- idempotency key -- on timeout/ambiguity the worker queries status by client_order_id,
-- never blind-retries a POST. CLAUDE.md invariant #5: never UPDATE/DELETE. Because an
-- order's status legitimately changes over its lifecycle (submitted -> filled/rejected/
-- cancelled), "append-only" here means each status transition is a NEW row referencing
-- the prior one via previous_order_id, not a mutation of the original row. The unique,
-- never-reused client_order_id ties the whole chain together and is what Webull itself
-- uses for idempotent submission.

create table orders (
    id uuid primary key default gen_random_uuid(),
    client_order_id text not null unique,
    decision_id uuid not null references decisions (id),
    previous_order_id uuid references orders (id),
    broker_order_id text,
    symbol text not null,
    side text not null
        constraint orders_side_valid check (side in ('buy', 'sell')),
    order_type text not null
        constraint orders_order_type_valid check (
            order_type in ('market', 'limit', 'stop', 'stop_limit')
        ),
    status text not null
        constraint orders_status_valid check (
            status in (
                'pending', 'submitted', 'partially_filled', 'filled',
                'cancelled', 'rejected', 'expired'
            )
        ),
    quantity numeric(18, 6) not null
        constraint orders_quantity_positive check (quantity > 0),
    limit_price numeric(14, 4),
    stop_price numeric(14, 4),
    filled_quantity numeric(18, 6) not null default 0
        constraint orders_filled_quantity_nonnegative check (filled_quantity >= 0),
    average_fill_price numeric(14, 4),
    is_paper boolean not null default true,
    submitted_at timestamptz not null default now(),
    broker_acknowledged_at timestamptz,
    terminal_at timestamptz,
    rejection_reason text,
    created_at timestamptz not null default now()
);

comment on table orders is
    'Append-only audit log: every order submitted to Webull, keyed by client_order_id for idempotency (CLAUDE.md invariant #4). Never UPDATE/DELETE -- status transitions are new rows chained via previous_order_id.';
comment on column orders.client_order_id is
    'Idempotency key generated by the worker and written to this table BEFORE the order is submitted to Webull. On timeout/ambiguity, the worker queries Webull order status by this ID -- never blind-retries a POST.';
comment on column orders.decision_id is
    'The decisions row (rules-engine output) that caused this order, completing the decision -> order -> trade audit chain.';
comment on column orders.previous_order_id is
    'If this row represents a status transition of an earlier submission (e.g. fill update, cancellation), links to that prior orders row. NULL for the initial submission.';
comment on column orders.broker_order_id is
    'Webull-assigned order ID once acknowledged. NULL until the broker responds.';
comment on column orders.is_paper is
    'TRUE for paper-environment orders, FALSE for live. Defaults TRUE -- per CLAUDE.md, live orders require explicit owner promotion and separate Webull keys/Railway environment.';

create index orders_decision_id_idx on orders (decision_id);
create index orders_symbol_idx on orders (symbol);
create index orders_status_idx on orders (status);
create index orders_submitted_at_idx on orders (submitted_at desc);
create index orders_previous_order_id_idx on orders (previous_order_id);

create trigger orders_prevent_update
    before update on orders
    for each row
    execute function reject_update_or_delete();

create trigger orders_prevent_delete
    before delete on orders
    for each row
    execute function reject_update_or_delete();

alter table orders enable row level security;

-- Owner may only read. Orders are written exclusively by the worker via service_role
-- (bypasses RLS) as part of the audited execution path -- never by the dashboard.
create policy orders_select_owner on orders
    for select
    to authenticated
    using (is_app_owner());

-- orders_current: the latest (terminal, i.e. leaf-of-chain) row for every order
-- lifecycle, plus the client_order_id of the chain's root submission. Because each
-- status transition is a new row linked via previous_order_id rather than a mutation
-- (see file header), finding "where does this order stand right now" otherwise requires
-- hand-walking previous_order_id chains in application/reconciliation code. This view
-- does that walk once, in SQL.
--
-- `security_invoker = true` (Postgres 15+, matches Supabase's Postgres version) makes
-- the view run with the privileges *and* RLS policies of the querying role rather than
-- the view owner's -- so orders_select_owner still applies per-row exactly as it does
-- against the base table. The view carries no privileges of its own beyond what the
-- underlying orders table already grants; it is not a new RLS surface, just a SELECT-only
-- convenience over the existing one.
create view orders_current
with (security_invoker = true)
as
with recursive order_chain as (
    -- anchor: root row of every chain (the initial submission, no previous_order_id)
    select
        o.id,
        o.id as chain_root_id,
        o.client_order_id as chain_root_client_order_id
    from orders o
    where o.previous_order_id is null

    union all

    -- recursive: walk forward from each root, following previous_order_id links
    select
        o.id,
        oc.chain_root_id,
        oc.chain_root_client_order_id
    from orders o
    join order_chain oc on o.previous_order_id = oc.id
)
select
    o.*,
    oc.chain_root_id,
    oc.chain_root_client_order_id
from orders o
join order_chain oc on o.id = oc.id
where not exists (
    -- terminal = no later row in the chain points back to this one
    select 1 from orders nxt where nxt.previous_order_id = o.id
);

comment on view orders_current is
    'One row per order lifecycle: the terminal (latest) orders row in each previous_order_id chain, plus chain_root_id/chain_root_client_order_id identifying the original submission. security_invoker = true, so orders_select_owner RLS applies per underlying row -- no separate grant needed.';
